#!/usr/bin/python
# -*- coding: utf-8 -*-
'''
Copyright (C) 2010 Karsten König <KarstenKoenig@gmx.net>

This is a simple rename-tool with some nice options written in Python with PyQt4.

I started the development because under Mac OS X doesn’t exist a free alternative to 
“NameMangler” as far as I know. Actually, I work under Linux and alternatives like 
pyRenamer are in my opinion to overcharged for some simple rename-processes. So here 
it is: cuteRenamer
'''

'''
This is just a script to start the main program
'''

from cuteRenamer.classes import MainWindow
from PyQt4.QtGui import QApplication
from sys import exit

app = QApplication(["cuteRenamer"])
    
print "Create the window"
mainWindow = MainWindow()
mainWindow.show()
    
print "Start the application"
exit(app.exec_())