#!/usr/bin/python

from cuteRenamer.classes import QtGui, MainWindow
from sys import exit

app = QtGui.QApplication(["cuteRenamer"])
    
print "Create the window"
mainWindow = MainWindow()
mainWindow.show()
    
print "Start the application"
exit(app.exec_())